export const channels = {
  GET_GLOBAL_CONFIG: 'GET_GLOBAL_CONFIG',
  SET_GLOBAL_CONFIG: 'SET_GLOBAL_CONFIG',
  WRITE_GLOBAL_CONFIG: 'WRITE_GLOBAL_CONFIG',
  GET_MODE_CONFIG: 'GET_MODE_CONFIG',
  SET_MODE_CONFIG: 'SET_MODE_CONFIG',
  GET_MODE_CONFIG_LIST: 'GET_MODE_CONFIG_LIST',
  SET_MODE_CONFIG_LIST: 'SET_MODE_CONFIG_LIST',
  GET_MODE_CONFIG_LIST_BY_MODE: 'GET_MODE_CONFIG_LIST_BY_MODE',
  OPEN_DIRECTORY: 'OPEN_DIRECTORY',
  GET_FILE_LIST: 'GET_FILE_LIST',
  GET_FILE_CONTENT: 'GET_FILE_CONTENT',
  SET_FILE_CONTENT: 'SET_FILE_CONTENT',
  GET_FILE_CONTENT_BY_PATH: 'GET_FILE_CONTENT_BY_PATH',
  SET_FILE_CONTENT_BY_PATH: 'SET_FILE_CONTENT_BY_PATH',
  GET_FILE_CONTENT_BY_PATH_LIST: 'GET_FILE_CONTENT_BY_PATH_LIST'
}
